"""initial schema

Revision ID: 601e7aa74c38
Revises: 
Create Date: 2026-08-12 13:45:36.758842

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '601e7aa74c38'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('denials',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('source_company', sa.String(length=128), nullable=False),
    sa.Column('raw_text', sa.Text(), nullable=False),
    sa.Column('payer', sa.String(length=255), nullable=False),
    sa.Column('claim_ref', sa.String(length=64), nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.Enum('new', 'processing', 'classified', 'appeal_drafted', 'needs_review', 'approved', 'rejected', name='denial_status'), server_default='new', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_denials_source_company', 'denials', ['source_company'], unique=False)
    op.create_index('ix_denials_source_company_status', 'denials', ['source_company', 'status'], unique=False)
    op.create_index('ix_denials_status', 'denials', ['status'], unique=False)
    op.create_table('eval_runs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('run_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('accuracy_score', sa.Float(), nullable=True),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('git_commit', sa.String(length=40), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('appeals',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('denial_id', sa.UUID(), nullable=False),
    sa.Column('draft_text', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('draft', 'approved', 'rejected', 'sent', name='appeal_status'), server_default='draft', nullable=False),
    sa.Column('reviewer', sa.String(length=128), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['denial_id'], ['denials.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_appeals_denial_id', 'appeals', ['denial_id'], unique=False)
    op.create_table('classifications',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('denial_id', sa.UUID(), nullable=False),
    sa.Column('category', sa.Enum('coding_error', 'missing_information', 'medical_necessity', 'timely_filing', 'eligibility', 'duplicate_claim', name='classification_category'), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('model_version', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['denial_id'], ['denials.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_classifications_denial_id', 'classifications', ['denial_id'], unique=False)
    op.create_table('corrections',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('denial_id', sa.UUID(), nullable=False),
    sa.Column('field_corrected', sa.String(length=128), nullable=False),
    sa.Column('old_value', sa.Text(), nullable=False),
    sa.Column('new_value', sa.Text(), nullable=False),
    sa.Column('corrected_by', sa.String(length=128), nullable=False),
    sa.Column('corrected_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['denial_id'], ['denials.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_corrections_denial_id', 'corrections', ['denial_id'], unique=False)
    op.create_table('extractions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('denial_id', sa.UUID(), nullable=False),
    sa.Column('extracted_fields', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('model_version', sa.String(length=64), nullable=False),
    sa.Column('prompt_version', sa.String(length=64), nullable=False),
    sa.Column('raw_model_output', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['denial_id'], ['denials.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_extractions_denial_id', 'extractions', ['denial_id'], unique=False)
    op.create_table('token_usage',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('denial_id', sa.UUID(), nullable=True),
    sa.Column('stage', sa.Enum('extraction', 'classification', 'appeal_drafting', name='token_usage_stage'), nullable=False),
    sa.Column('input_tokens', sa.Integer(), nullable=False),
    sa.Column('output_tokens', sa.Integer(), nullable=False),
    sa.Column('estimated_cost_usd', sa.Numeric(precision=10, scale=6), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['denial_id'], ['denials.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_token_usage_denial_id', 'token_usage', ['denial_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_token_usage_denial_id', table_name='token_usage')
    op.drop_table('token_usage')
    op.drop_index('ix_extractions_denial_id', table_name='extractions')
    op.drop_table('extractions')
    op.drop_index('ix_corrections_denial_id', table_name='corrections')
    op.drop_table('corrections')
    op.drop_index('ix_classifications_denial_id', table_name='classifications')
    op.drop_table('classifications')
    op.drop_index('ix_appeals_denial_id', table_name='appeals')
    op.drop_table('appeals')
    op.drop_table('eval_runs')
    op.drop_index('ix_denials_status', table_name='denials')
    op.drop_index('ix_denials_source_company_status', table_name='denials')
    op.drop_index('ix_denials_source_company', table_name='denials')
    op.drop_table('denials')
    # ### end Alembic commands ###
